### ISSUE TITLE
"Security" doc inconsistent for thin client connection parameters via C++

### ISSUE THREAD

**Issue by pasniak** [gridgain/gridgain#1613]
It is unclear how to configure thin client connection parameters via C++. "Security" doc says "This API is not presently available for C++. You can use XML configuration". While "Thin Clients/C++ Thin Client" page lists SetUser/SetPassword methods.

**Comment by alamar** [comment]
Hello!

The page that you're referring describes how to set up password security. Thin client can use password security by providing username/password pair but it cannot set up password security for cluster. Hence, this is correct. Neither Java or XML configuration describe how to configure thin client connection parameters.

Hope it helps,
