### ISSUE TITLE
gridgain could load balance with thin driver?

### ISSUE THREAD

**Issue by zhangzl0119** [gridgain/gridgain#834]
I have a  gridgain  cluster with 3 nodes of . I connect with JDBC thin driver.
when I have a insert pressure test with large data, only one node's CPU is near 100,
others CPU is near 0.
GridGain cluster could do a load balance?

**Comment by alamar** [comment]
Please use our Forums for general discussion of GridGain:
https://forums.gridgain.com/home
Let's keep GitHub Issues for specific bug reports.
